version: "3.8"
services: 
  hostie-prod:
    container_name: hostie-prod
    build: .
    environment:
      - NEXTAUTH_URL=https://thehostie.com
      - NEXT_PUBLIC_NEXTAUTH_URL=https://thehostie.com
      - NEXTAUTH_SECRET=sadsadsa
      - HOST=0.0.0.0
    restart: always 
    ports:
      - 3000:3000

networks:
  hostie-network:
    driver: bridge